### ISSUE TITLE
help errors when installing wallet

### ISSUE THREAD

**Issue by jocelinocrs** [VulcanoCrypto/Vulcano#1]
hello i am trying to install the new wallet of the vulcano core this damage these mistakes me help
I'm using
https://github.com/VulcanoCrypto/Vulcano/blob/master/doc/build-unix.md
........................................................................................
 CXX      libbitcoin_server_a-init.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:4126: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/root/vulcano_novo/src'
Makefile:7713: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/vulcano_novo/src'
Makefile:603: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by collinTak** [comment]
I think you entered the install command twice.
Format the VPS and reinstall it.
Good luck.

**Comment by isy348** [comment]
Good and trusted project

**Comment by heavysunnyz** [comment]
Good
