### ISSUE TITLE
withdraw VULC from yobit to coinexchange not received

### ISSUE THREAD

**Issue by ailaah** [VulcanoCrypto/Vulcano#5]
dear....

I am unable to find this transaction ID on the block explorer. this is the link with txid i get https://explorer.vulcano.io/#/tx/0fd6ff83381296eb7925ea189bd3fb7073a6dea7d36395473630227266438b86 

this is my address for receive VULC VXxovGJk3qBeVr8DbnUxvvsDhkCQhpNvQc 

time to withdraw detaile i receive  Info 2018-12-14 22:40:44 
117676.53690618 VULC 0fd6ff83381296eb7925ea189bd3fb7073a6dea7d36395473630227266438b86 

please fix it thank you

**Comment by ariondev** [comment]
Unfortunately, even after numerous requests Yobit has not updated their wallet and are on a very old version. They have not warned their clients but we have posted warnings everywhere we can. I'm so sorry but your coins are lost

**Comment by BitBenderMedia** [comment]
It is unfortunate that you lost your coins. Despite attempts to get them to update their wallet and transition to the correct chain, they have not done so.
